#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Cursor
hyprctl setcursor "Catppuccin-Mocha-Blue-Cursors" 36
#hyprctl setcursor oreo_spark_light_pink_cursors 24
# notification daemon
dunst &

fcitx5 -d &

# waybar
~/.config/hypr/scripts/waybar.sh &

# wallpaper
mpvpaper HDMI-A-1 -p -s ~/.config/hypr/wallpaper/chino.mp4 -o " --loop --no-audio " -f &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
