alias c='clear'
alias d='dolphin --platformtheme qt5ct'
alias n='/home/feng/Documents/MyNotes/'
alias ws='cd ~/Data/PycharmProjects/eol;nvim'
alias cdiff='colordiff'
alias gg='git clone'
alias ipy='ipython'
alias kc='kdeconnect-cli'
alias ls='ls --color=always'
alias l='ls -la'
alias lg='lazygit'
alias ra='ranger'
alias sra='sudo -E ranger'
alias reload='source ~/.zshrc'
alias ez='ranger ~/.myconfig/zshconfig'
alias eh='ranger ~/.myconfig/home_config'
alias pa=ALL_PROXY=socks://127.0.0.1:10808
alias ea='vim ~/.config/awesome/rc.lua'
alias ssta='systemctl start'
alias ssto='systemctl stop'
alias sresa='systemctl restart'
alias vmware='prime-run vmware'
alias cp='cp -av'
alias windows-binaries='cd ~/MyTools/windows-binaries;ls'
alias wine32="WINEARCH=win32 WINEPREFIX=~/win32"
alias windows-resources='cd ~/MyTools/windows-resources;ls'
alias e-pacman-list='nvim /home/feng/list/pacman.list'
alias e-awesome-rc='nvim /home/feng/.config/awesome/rc.lua'
alias e-awesome-theme='nvim /home/feng/.config/awesome/themes/gtk/theme.lua'


