#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/rofi"
RASI="$DIR/launcher.rasi"

# rofi text dialog to get password
rofi -dmenu \
	-password \
	-i \
	-p "Root" \
	-theme ${RASI}
