#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/rofi"
RASI="$DIR/launcher.rasi"

# Run
rofi \
	-show drun \
	-theme ${RASI}
