#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/rofi"
RASI="$DIR/powermenu.rasi"
CNFR="$DIR/confirm.rasi"

# Theme Elements
prompt="$(hostname) ($(echo $DESKTOP_SESSION))"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	option_1=" Suspend"
	option_2=" Logout"
	option_3=" Lock"
	option_4=" Reboot"
	option_5=" Shutdown"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
fi
cnflayout=$(cat ${CNFR} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$cnflayout" == 'NO' ]]; then
	yes=' Yes'
	no=' No'
else
	yes=''
	no=''
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${CNFR}
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		${1} && ${2} && ${3}
	else
		exit
	fi
}

screen_locker() {
	swaylock \
		--screenshots \
		--indicator \
		--clock \
		--inside-wrong-color 000000 \
		--ring-wrong-color 11111b \
		--inside-clear-color a6e3a1 \
		--ring-clear-color 11111b \
		--inside-ver-color 89b4fa \
		--ring-ver-color 11111b \
		--text-color f5c2e7 \
		--indicator-radius 80 \
		--indicator-thickness 5 \
		--effect-vignette 0.5:0.5 \
		--ring-color 11111b \
		--key-hl-color f5c2e7 \
		--line-color 313244 \
		--inside-color 00000000 \
		--separator-color 00000000 \
		--fade-in 0.1 &
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		confirm_run 'systemctl hybrid-sleep'
	elif [[ "$1" == '--opt2' ]]; then
		confirm_run 'hyprctl dispatch exit'
	elif [[ "$1" == '--opt3' ]]; then
		screen_locker
	elif [[ "$1" == '--opt4' ]]; then
		confirm_run 'systemctl reboot'
	elif [[ "$1" == '--opt5' ]]; then
		confirm_run 'systemctl poweroff'
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
	run_cmd --opt1
	;;
$option_2)
	run_cmd --opt2
	;;
$option_3)
	run_cmd --opt3
	;;
$option_4)
	run_cmd --opt4
	;;
$option_5)
	run_cmd --opt5
	;;
esac
