#!/usr/bin/bash
swww init
swww img $1 --transition-type outer --transition-pos "$(hyprctl cursorpos | awk -F ', ' '{print $1}'), $(hyprctl cursorpos | awk -F ', ' '{print 1079-$2}')" --transition-duration 3
